import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex gap-8 max-h-dvh overflow-hidden">
      <aside>Sidenav</aside>
      <main className="overflow-y-scroll">{children}</main>
    </div>
  );
}
