import type { Metadata } from 'next';
import SideNav from '../_ui/SideNav';

// TODO: Update metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function SidebarLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      id="sidebar-layout"
      className="grid grid-cols-[12rem_1fr] h-screen gap-4"
    >
      <aside>
        <SideNav />
      </aside>
      <main className="h-full overflow-y-auto">{children}</main>
    </div>
  );
}
