import type { Metadata } from 'next';
import SideNav, {
  NavBar as SideNavNavBar,
  ToggleButton as SideNavToggle,
} from '../_ui/SideNav';

// TODO: Update metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function SidebarLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      id="sidebar-layout"
      className="grid grid-cols-[12rem_1fr] h-screen gap-4 max-bp-navbar-mobile:flex max-bp-navbar-mobile:flex-col"
    >
      <aside className="max-bp-navbar-mobile:absolute">
        <SideNav>
          <SideNavNavBar />
          <SideNavToggle className="fixed top-2 right-4" />
        </SideNav>
      </aside>
      <main className="h-full overflow-y-auto">{children}</main>
    </div>
  );
}
