import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import TextRegular from './_ui/typography/TextRegular';
import { Providers } from './_providers/Providers';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

// TODO: Update metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased overflow-y-scroll text-text bg-background`}
      >
        <Providers>
          <TextRegular
            id="wrapper-all-always"
            className="w-full overflow-x-hidden"
          >
            {children}
          </TextRegular>
        </Providers>
      </body>
    </html>
  );
}
