import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import TextRegular from './_ui/typography/TextRegular';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

// TODO: Update metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased overflow-y-scroll text-text bg-background`}
      >
        <TextRegular
          id="wrapper-all-always"
          className="w-full overflow-x-hidden"
        >
          {children}
        </TextRegular>
      </body>
    </html>
  );
}
// TODO NEXT Typography components
// base --- 2 --- DONE
//
// lg --- 3
// xl --- 3 (1 layout)
// 3xl --- 4
// 4xl --- 2
// 7xl --- 1
